Add app-serving workflow
openinfradev/tks-flow pull request #92
Opened 2022-06-10 02:38 UTC by robertchoi80

app-serving MVP 시연을 위한 workflow 초안 추가합니다. 
우선 신속한 구현을 위해 하나의 step으로 구성되어 있고, 향후 실제 서비스시에는 API 분할에 따라 step이 나뉘어질 것으로 보입니다. 
app profile 선택하는 부분도 현재는 빠져있고 향후 추가 예정입니다. 

<참고사항>
- 바로 테스트해보실 수 있게 sample java app을 빌드해놓은 제 개인 repo url 을 default param으로 넣어두었습니다. 
- dockerhub 상에 동적으로 repository를 만들어주어야 100% 자동화가 될텐데, 그부분은 현재 수동으로 수행하였습니다. (차후 harbor 등 다른 Registry를 쓸 수도 있으므로 굳이 Dockerhub API 써서 repo 생성하는 노가다는 하지 않았습니다)
- 마지막의 endpoint 보여주는 부분은 실제 서비스에선 app-serving-LCM 에서 app-serving-CLI로 전달해서 보여줄 내용인데, 아직 해당 컴포넌트들이 없기에 임시로 workflow에 넣어두었습니다.

2022-06-10 02:57 UTC, robertchoi80 commented
배포된 app 상태 체크하는 부분도 추가되어야 합니다.  (기본적인 Pod 상태 체크 등)

2022-06-10 03:54 UTC, ktkfree commented on app_serving/serve-java-app.yaml
> +
이미지 버전이 latest 로 고정이고, manifest 도 고정인 것 같은데, 이렇게 하면 2번째 실행할 경우(update) deploy 가 될까요?
강제로 pod 를 delete 하는 action 이 필요하지 않을까 합니다.

2022-06-10 06:04 UTC, bluejayA commented
연결되는 이슈 ticket이 없습니다. 연결 부탁드릴께요

2022-06-13 00:41 UTC, robertchoi80 commented on app_serving/serve-java-app.yaml
> +
일단 정말 최소 기능만 퀵하게 구현해봤는데, 말씀하신 update 기능까지는 넣어서 시연하는 것이 좋겠네요. 아예 요청시 version param을 명시적으로 받아 Image tag로 사용하게 하는건 어떨까요?

2022-06-13 02:09 UTC, ktkfree commented on app_serving/serve-java-app.yaml
> +
네, 그 방식이 가장 좋을 것 같습니다~

2022-06-13 05:18 UTC, robertchoi80 commented on app_serving/serve-java-app.yaml
> +
태그 지정하는 부분 추가하였습니다.

2022-06-13 05:18 UTC, robertchoi80 commented
> 연결되는 이슈 ticket이 없습니다. 연결 부탁드릴께요

이슈 연결했습니다

2022-06-14 04:50 UTC, ktkfree approved these changes

2022-06-29 07:56 UTC, Jaesang requested changes

2022-06-29 07:56 UTC, Jaesang commented on app_serving/serve-java-app.yaml
> +        kubectl apply -f ./manifest.yaml -n {{workflow.parameters.app_name}}
App Namespace를 생성하는 부분이 없어서, 최초 실행시 에러가 날 것 같습니다.

2022-06-29 08:12 UTC, zugwan commented on app_serving/serve-java-app.yaml
> +        #app_root=${app_repo##*\/}
주석 처리보다는 제거하는 것이 좋을 듯 합니다.

2022-06-29 08:16 UTC, robertchoi80 commented on app_serving/serve-java-app.yaml
> +        kubectl apply -f ./manifest.yaml -n {{workflow.parameters.app_name}}
manifest에 namespace 가 포함되어있습니다.  제가 service.yaml 안에 포함시켜놓아서 혼동하셨겠네요

2022-06-29 08:19 UTC, Jaesang commented on app_serving/serve-java-app.yaml
> +        kubectl apply -f ./manifest.yaml -n {{workflow.parameters.app_name}}
아하, 거기에 들어갈수있군요

2022-06-29 08:36 UTC, robertchoi80 commented on app_serving/serve-java-app.yaml
> +        #app_root=${app_repo##*\/}
제거했습니다

2022-06-29 08:41 UTC, robertchoi80 commented on app_serving/serve-java-app.yaml
> +        kubectl apply -f ./manifest.yaml -n {{workflow.parameters.app_name}}
https://github.com/openinfradev/app-serve-template/commit/a7422ee5bef9d410fd8403a66519baf6d361c034 에서 수정하였습니다.

2022-06-29 09:10 UTC, ktkfree commented on app_serving/serve-java-app.yaml
> +          kustomize build base > manifest.yaml
kustomize 가 익숙치 않아 무엇이 best practice 인지는 모르겠습니다만.
base 를 빌드하는 것보다 medium overlay 를 만들어서 명시적으로 medium 을 빌드하는건 어떨까요?

우리도 site 를 지정해서 빌드하지 base-yaml 을 직접 사용하지 않는 것 처럼...

2022-06-29 09:13 UTC, ktkfree commented on app_serving/serve-java-app.yaml
> +          kustomize build base > manifest.yaml
추후에...

2022-06-29 09:13 UTC, ktkfree approved these changes

2022-06-29 09:53 UTC, zugwan commented on app_serving/serve-java-app.yaml
> +        sed -i "s/IMAGEURL/${image_name_alt}/g" ./manifest.yaml
sed 기본 delimeter가 / 라서 이미지 이름 치환하는데 문제가 있어 image_name_alt 변수를 추가로 할당하신 것이면 ```sed -i "s#IMAGEURL#${image_name}#g" ./manifest.yaml``` 처럼 delimeter를 '#'으로 사용하면 image_name 변수 그대로 사용 가능합니다.

2022-06-29 13:25 UTC, robertchoi80 commented on app_serving/serve-java-app.yaml
> +        sed -i "s/IMAGEURL/${image_name_alt}/g" ./manifest.yaml
수정했습니다!  위에서 '/'를 '\/' 로 치환해서 image_name_alt로 넣는 과정에서 이미 다른 delimeter를 썼음에도 눈치를 못 챘었네요.

2022-06-29 13:28 UTC, robertchoi80 commented on app_serving/serve-java-app.yaml
> +          kustomize build base > manifest.yaml
네 그게 더 깔끔하네요. 수정했습니다!

2022-06-30 01:03 UTC, zugwan approved these changes

2022-06-30 01:21 UTC, Jaesang approved these changes

2022-06-30 01:21 UTC, merged