support multi cluster api infra providers
openinfradev/tks-flow pull request #96
Opened 2022-06-17 10:21 UTC by zugwan

아래 PR들이 먼저 반영되어야 합니다.
1. https://github.com/openinfradev/helm-charts/pull/126
2. https://github.com/openinfradev/decapod-base-yaml/pull/164
3. https://github.com/openinfradev/decapod-site/pull/89
4. https://github.com/openinfradev/decapod-flow/pull/93

기존 cluster-api-aws 차트에서 수행하던 인프라 프로바이더 공통 작업을 템플릿으로 이동하였고 infra_provider 파라미터를 추가하여 프로바이더 별로 분기할 수 있도록 하였습니다.

2022-06-22 01:00 UTC, ktkfree commented
코드 변경량이 많네요.. 이건 싱크때 한번 공유해주시면 리뷰가 수월하겠습니다.

2022-06-22 02:43 UTC, ktkfree commented
tks-cluster-lcm 도 변경이 되어야 할 것 같습니다. 이건 제가 변경후 PR 올리겠습니다.

2022-06-22 02:47 UTC, ktkfree commented on tks-cluster/create-usercluster-wftpl.yaml
>            name: manage-internal-communication
이것도 aws 전용이므로 아래가 포함되어야 하겠습니다.
when: "{{workflow.parameters.infra_provider}} == aws"

2022-06-22 03:10 UTC, ktkfree commented
> tks-cluster-lcm 도 변경이 되어야 할 것 같습니다. 이건 제가 변경후 PR 올리겠습니다.

아 이건, ticket 이 이미 있는 건이군요..

2022-06-22 05:07 UTC, zugwan commented on tks-cluster/create-usercluster-wftpl.yaml
>            name: manage-internal-communication
수정하였습니다.

2022-06-22 05:27 UTC, robertchoi80 requested changes

2022-06-22 05:27 UTC, robertchoi80 commented on tks-cluster/create-usercluster-wftpl.yaml
> +          kubectl wait --for=condition=Ready --timeout=600s awscluster -n $CLUSTER_ID $CLUSTER_ID
awscluster 체크하는 부분이 공통 로직 쪽에 들어가있는데, 이게 아까 싱크 때 수정할 거라고 하신 부분이었나요?

2022-06-22 06:13 UTC, zugwan commented on tks-cluster/create-usercluster-wftpl.yaml
> +          kubectl wait --for=condition=Ready --timeout=600s awscluster -n $CLUSTER_ID $CLUSTER_ID
네, 수정 중입니다.

2022-06-22 06:28 UTC, zugwan commented on tks-cluster/create-usercluster-wftpl.yaml
> +          kubectl wait --for=condition=Ready --timeout=600s awscluster -n $CLUSTER_ID $CLUSTER_ID
프로바이더 공통으로 사용되도록 kcp (kubeadmcontrolplanes)의 Available (KubeadmControlPlane API Server is ready to receive requests) 조건이 만족할 때까지 기다리는 것으로 변경하였습니다.

2022-06-24 02:54 UTC, ktkfree commented on tks-cluster/create-usercluster-wftpl.yaml
> +          yes | argocd login --insecure $ARGO_SERVER --username $ARGO_USERNAME --password $ARGO_PASSWORD
중요한건 아닙니다. --plaintext 를 추가하면 "yes |" command 를 삭제할 수 있을 것 같습니다.

2022-06-24 02:54 UTC, ktkfree approved these changes

2022-06-24 06:08 UTC, robertchoi80 approved these changes

2022-06-24 06:08 UTC, ktkfree approved these changes

2022-06-24 06:08 UTC, merged